// <auto-generated />
using BizimMarket.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BizimMarket.Migrations
{
    [DbContext(typeof(BizimMarketContext))]
    partial class BizimMarketContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BizimMarket.Models.Kategori", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("KategoriId");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            KategoriId = 1,
                            KategoriAdi = "Fırın,Pastane"
                        },
                        new
                        {
                            KategoriId = 2,
                            KategoriAdi = "Meze,Hazır Yemek"
                        },
                        new
                        {
                            KategoriId = 3,
                            KategoriAdi = "Meyve,Sebze"
                        });
                });

            modelBuilder.Entity("BizimMarket.Models.Urun", b =>
                {
                    b.Property<int>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("ResimYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UrunId");

                    b.HasIndex("KategoriId");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            UrunId = 1,
                            Fiyat = 22.90m,
                            KategoriId = 1,
                            ResimYolu = "minikSandvic.jpg",
                            UrunAdi = "Minik Sandviç 10'Lu"
                        },
                        new
                        {
                            UrunId = 2,
                            Fiyat = 9.90m,
                            KategoriId = 1,
                            ResimYolu = "papatyaEkmek.jpg",
                            UrunAdi = "Papatya Ekmek 300 G (Küçük) ( Yeni )"
                        },
                        new
                        {
                            UrunId = 3,
                            Fiyat = 24.95m,
                            KategoriId = 2,
                            ResimYolu = "simit.jpg",
                            UrunAdi = "Superfresh 7/24 Fırından Simit 400 G"
                        },
                        new
                        {
                            UrunId = 4,
                            Fiyat = 44.90m,
                            KategoriId = 2,
                            ResimYolu = "comboSogan.jpg",
                            UrunAdi = "Feast Combo Soğan Halkalı 740 G"
                        },
                        new
                        {
                            UrunId = 5,
                            Fiyat = 19.90m,
                            KategoriId = 3,
                            ResimYolu = "domates.jpg",
                            UrunAdi = "Domates Kokteyl Kg"
                        },
                        new
                        {
                            UrunId = 6,
                            Fiyat = 24.95m,
                            KategoriId = 3,
                            ResimYolu = "karnabahar.jpg",
                            UrunAdi = "Karnabahar Kg"
                        },
                        new
                        {
                            UrunId = 7,
                            Fiyat = 43.90m,
                            KategoriId = 3,
                            ResimYolu = "biber.jpg",
                            UrunAdi = "Biber Acı Şili Kırmızı Kg"
                        });
                });

            modelBuilder.Entity("BizimMarket.Models.Urun", b =>
                {
                    b.HasOne("BizimMarket.Models.Kategori", "Kategori")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("BizimMarket.Models.Kategori", b =>
                {
                    b.Navigation("Urunler");
                });
#pragma warning restore 612, 618
        }
    }
}
